### ISSUE TITLE
Can not handle bar character

### ISSUE THREAD

**Issue by michaelmesser** [paf31/typescript-docs#5]
When parsing a valid d.ts file which contains the following line, typescript-docs crashes.

`type verbTense = "present" | "past" | "future"`

```
Reading input file...
Lexing tokens...
Error from lexer: Error: Unexpected character "|" at line 5, column 30
    at Object.error (/usr/local/lib/node_modules/typescript-docs/index.js:683:12)
    at go (/usr/local/lib/node_modules/typescript-docs/index.js:2883:103)
    at /usr/local/lib/node_modules/typescript-docs/index.js:2209:162
    at __do (/usr/local/lib/node_modules/typescript-docs/index.js:2897:23)
    at /usr/local/lib/node_modules/typescript-docs/index.js:635:20
    at /usr/local/lib/node_modules/typescript-docs/index.js:635:24
    at /usr/local/lib/node_modules/typescript-docs/index.js:698:18
    at Object.runPure (/usr/local/lib/node_modules/typescript-docs/index.js:642:14)
    at Object.PS.Language_TypeScript_Lexer.lex (/usr/local/lib/node_modules/typescript-docs/index.js:2895:34)

    at __do (/usr/local/lib/node_modules/typescript-docs/index.js:5409:55)
```

**Comment by paf31** [comment]
This library isn't really maintained any more. It only supports an older version of TypeScript, which didn't have union types.
